apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-todo-app-deploy
spec:
  selector:
    matchLabels:
      app: todo-app
  replicas: 2
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: suhail12/mytodoapp:stable-latest

