name: Tag Change Workflow

on:
  repository_dispatch:
    types:
      - tag-change

jobs:
  handle_tag_change:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Display tag name
        run: echo "Tag name: ${{ steps.extract_tag.outputs.TAG_NAME }}"
